export default({
    name:'project',
    title:"Project",
    type:'document',
    fields:[
        {
            name:'title',
            type:'string',

        },
        {
            name:"date",
            type:'datetime'
        },
        {
            name:'place',
            type:'string'
        },
        {
            name:'description',
            type:'text'
        },
        {
            name:'projectType',
            title:"ProjectType",
            type:"string",
            options:{
                list:[
                    {value:"Personal",title:'Personal'},
                    {value:"client",title:"Client"}
                ]
            }
        },
        {
            name:'link',
            type:'url'
        },
        {
            name:'tags',
            type:"array",
            of:[
                {
                    type:'string'
                },
            ],
            options:{
                layout:"tags"
            }
        }
        
    ]
})